### ISSUE TITLE
When posting/updating content with raw/rendered fields, accepted parameter should not be nested

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-rest#13]
For example, if updating a course's content, the api should accept `content` as the parameter, the request should not require a submission of raw/rendered data via passing `content.raw` and/or `content.rendered`

Raw content should always be supplied directly to the main property. The object is passed during `GET` requests.

**Comment by eri-trabiccolo** [comment]
Accidentally I was already **only** accepting the `'content' => string` format when creating/updating. :D

**Comment by thomasplevy** [comment]
Good :-D

The spec needs to make this explicit though, carry on with your mistake I'm working on figuring out how to update the spec accordingly

**Comment by eri-trabiccolo** [comment]
Yes sure, thanks!

**Comment by thomasplevy** [comment]
Documentation is unclear in WP Core but in practice it's possible to create/update a post with either of the following payloads for fields which __return__ an object with `rendered` and `raw` properties:

```json
{
    "content": "this is the raw html content"
}
```

Or:

```json
{
    "content": {
       "raw": "this is the raw html content"
    }
}
```

So the updated spec will allow for both:

![API_Reference___ReDoc](https://user-images.githubusercontent.com/1290739/60463216-3b47b900-9c00-11e9-811f-9769217273ed.jpg)
![API_Reference___ReDoc](https://user-images.githubusercontent.com/1290739/60463234-47cc1180-9c00-11e9-8450-b76f333128b0.jpg)

Example spec:
```yml
description: Post title.
oneOf:
  - type: string
    description: Raw title.
    example: Getting Started with LifterLMS
    writeOnly: true
  - type: object
    properties:
      rendered:
        type: string
        description: Rendered title.
        example: Getting Started with LifterLMS
        readOnly: true
      raw:
        type: string
        description: Raw title. Useful when displaying title in the WP Block Editor. Only returned in `edit` context.
        example: Getting Started with LifterLMS
```
