### ISSUE TITLE
Create github actions to replace travis to test openapi etc.

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-rest#241]
.travis.yml containing the following:
```
jobs:
  include:
  - name: "Test OpenAPI Spec"
    language: node_js
    node_js: lts/*
    before_install:
    install:
      - npm ci
    script:
      - npm run test
  - stage: deploy
    language: node_js
    node_js: lts/*
    if: branch = trunk AND env(GH_TOKEN) IS present
    before_install:
    install:
      - npm ci
    script: npm run build:docs && npm run gh-pages
```
has been removed.
Those jobs should be replaced with gh actions.
